name: Build TIO on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'base-devel mingw-w64-x86_64-toolchain git'

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm

    - name: Set up build environment
      run: |
        # Set up the build environment using Meson
        meson setup builddir

    - name: Build
      run: |
        # Compile the project using Meson
        meson compile -C builddir
